# Service Details
spring.application.name=fairseat-booking
server.port=8083

# Core Concurrency Optimization
spring.threads.virtual.enabled=true

# Database Connection (Secured with Environment Variables)
spring.datasource.url=jdbc:postgresql://localhost:5434/booking_db
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configurations
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Distributed Lock Strategy Configuration
fairseat.lock.wait-time-seconds=2
fairseat.lock.lease-time-seconds=10

# Kafka Producer Configuration
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer

# Ensure Spring knows what packages are safe to serialize into JSON
spring.kafka.producer.properties.spring.json.add.type.headers=true