# Service Details
spring.application.name=fairseat-booking
server.port=8083

# Core Concurrency Optimization
spring.threads.virtual.enabled=true

# Database Connection (Secured with Environment Variables)
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME}
spring.datasource.username=${DB_USERNAME:fairseat_admin}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false