# Service Details
spring.application.name=fairseat-discovery
server.port=8082

# Database Connection (Secured with Environment Variables)
spring.datasource.url=jdbc:postgresql://localhost:5433/discovery_db
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false