# Service Setup
spring.application.name=fairseat-ticket
server.port=8085

# Completely Isolated Ticket Database
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5436/ticket_db}
spring.datasource.username=${POSTGRES_USER:admin}
spring.datasource.password=${POSTGRES_PASSWORD:admin}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}

# Kafka Consumer Configuration
spring.kafka.bootstrap-servers=${KAFKA_SERVERS:kafka:29092}
spring.kafka.consumer.group-id=ticket-generation-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# 1. Stop Infinite Loops (Poison Pill Defense)
# We tell Kafka to use an ErrorHandler first, which delegates to Jackson. If Jackson fails, the ErrorHandler catches it and drops the bad message instead of retrying forever.
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JacksonJsonDeserializer

# 2. Cross-Microservice Type Translation
# We tell Jackson how to translate BOTH Booking events AND Marketplace events!
spring.kafka.consumer.properties.spring.json.type.mapping=com.pfa.fairseatbooking.event.BookingConfirmedEvent:com.pfa.fairseatticket.event.BookingConfirmedEvent,com.pfa.fairseatmarketplace.event.TicketTransferredEvent:com.pfa.fairseatticket.event.TicketTransferredEvent

# Tell Jackson it's safe to deserialize JSON into our local event classes
spring.kafka.consumer.properties.spring.json.trusted.packages=com.pfa.fairseatticket.event
